### ISSUE TITLE
Semantic segmentation experiments

### ISSUE THREAD

**Issue by dxjid** [DensoITLab/TeachAugment#1]
Hello,

I would like to know how  to run the experiments for semantic segmentation with the available code, it seems that there are missing parts if so, would it be possible to publish them also.

thanks.

**Comment by perrying** [comment]
Semantic segmentation is not supported in this repository.

**Comment by perrying** [comment]
I don't plan to release the code but I can share some key component files to implement TeachAugment for semantic segmentation.
If you want them, please send an email: suzuki.teppei[at]core.d-itlab.co.jp
