### ISSUE TITLE
Question about the probability p_c and p_g

### ISSUE THREAD

**Issue by hchoi71** [DensoITLab/TeachAugment#2]
Thanks for this great work! I enjoyed reading this paper :)

I have a simple question regarding p_c and p_g. As described in your paper, you made p_c and p_g differentiable using relaxed Bernoulli distribution. Have you compared this setup with the random setting? For example, in a conventional Mixup augmentation, they usually pick up lambda which controls the strength of interpolation. aug_image = lam * img_1 + (1-lam) * img_2 where lam is a random variable distributed from beta distribution or etc.  

I was wondering if you have done this comparison between your setting and random setting for p_c and p_g. 

Thanks again :)

**Comment by perrying** [comment]
I have not evaluated the random setting.
